services:

  symfony:
    container_name: jee_symfony
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ}
    volumes:
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mariadb
      - mercure
    networks:
      - internal
    restart: unless-stopped

  mariadb:
    container_name: jee_mariadb
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jee
    volumes:
      - jee_mariadb_data:/config
    networks:
      - internal
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: jee_npm
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
    depends_on:
      - symfony
      - mariadb
    networks:
      - internal

  mercure:
    container_name: jee_mercure
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_JWT_SECRET}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_JWT_SECRET}"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    ports:
      - "9090:80"
    volumes:
      - jee_mercure_data:/data
      - jee_mercure_config:/config
    networks:
      - internal

networks:
  internal:

volumes:
  jee_mariadb_data:
  jee_mercure_data:
  jee_mercure_config: