services:

  symfony:
    container_name: jee_symfony
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mariadb

  mariadb:
    container_name: jee_mariadb
    image: mariadb:11.4.2
    restart: always
    environment:
      MARIADB_DATABASE: jee
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data/mariadb:/var/lib/mysql

  nginx-proxy-manager:
    container_name: jee_npm
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt

  # añadir tailscale
  # añadir s3
