services:

  symfony:
    container_name: jee_symfony
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mariadb
      - minio
      - mercure
    networks:
      - internal

  mariadb:
    container_name: jee_mariadb
    image: mariadb:11.4.2
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: jee
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - jee_mariadb_data:/var/lib/mysql
    networks:
      - internal

  nginx-proxy-manager:
    container_name: jee_npm
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
    depends_on:
      - symfony
      - mariadb
      - minio
    networks:
      - internal

  minio:
    container_name: jee_minio
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
      - jee_minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    networks:
      - internal

  mercure:
    container_name: jee_mercure
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_JWT_SECRET}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_JWT_SECRET}"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    ports:
      - "9090:80"
    volumes:
      - jee_mercure_data:/data
      - jee_mercure_config:/config
    networks:
      - internal

networks:
  internal:

volumes:
  jee_mariadb_data:
  jee_mercure_data:
  jee_mercure_config:
  jee_minio_data: