services:

  symfony:
    container_name: jee_symfony
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8000:80"

  mariadb:
    container_name: jee_mariadb
    image: mariadb:11.4.2
    restart: always
    environment:
      MARIADB_DATABASE: jee
      MARIADB_ROOT_PASSWORD: root
      APACHE_PORT: 8090
    ports:
      - "3336:3306"

  nginx-proxy-manager:
    container_name: jee_npm
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
