services:

  symfony: &symfony-template
    image: ${COMPOSE_PROJECT_NAME}-symfony:latest
    build:
      context: ./docker/php
      args:
        BUILD_ARGUMENT_ENV: dev
        XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        XDEBUG_VERSION: ${XDEBUG_VERSION}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-symfony
    ports:
      - "${WEB_PORT_HTTP}:8000"
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - mysql
      - rabbitmq
      - mail
    networks:
      - symfony

  supervisord:
    <<: *symfony-template
    container_name: ${COMPOSE_PROJECT_NAME}-supervisord
    expose: []
    ports: []
    command: ["/usr/bin/supervisord"]

  mariadb:
    image: mariadb:${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jee
    ports:
      - "3310:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - symfony

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq:delegated
    networks:
      - symfony

  mailpit:
    image: axllent/mailpit:latest
    container_name: ${COMPOSE_PROJECT_NAME}-mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - symfony

  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - symfony
    networks:
      - symfony

networks:
  symfony:
    name: symfony