login:
  path: /login
  controller: App\Apps\Web\Auth\Login\LoginController
  methods: [ POST ]

refresh_token:
  path: /refresh-token
  controller: App\Apps\Web\Auth\Refresh\GetTokenByRefreshController
  methods: [ POST ]