get_notifications:
  path: /notifications
  controller: App\Apps\Web\Notification\SearchNotifications\SearchNotificationsController
  methods: [ GET ]
  defaults: { auth: true }

mark_as_read:
  path: /notification/{id}/mark-as-read
  controller: App\Apps\Web\Notification\MarkAsRead\MarkAsReadController
  methods: [ PUT ]
  defaults: { auth: true }

