create_post:
  path: /post/{id}
  controller: App\Apps\Web\Post\Create\CreatePostController
  methods: [ PUT ]
  defaults: { auth: true }

find_post:
  path: /post/{id}
  controller: App\Apps\Web\Post\Find\FindPostController
  methods: [ GET ]
  defaults: { auth: true }

search_posts:
  path: /posts
  controller: App\Apps\Web\Post\Search\SearchPostsController
  methods: [ GET ]
  defaults: { auth: true }

add_post_comment:
  path: /post/{id}/comment
  controller: App\Apps\Web\Post\AddPostComment\AddPostCommentController
  methods: [ PUT ]
  defaults: { auth: true }

#like:
#  path: /post/{id}/like
#  controller: App\Apps\Web\Post\Like\LikePostController
#  methods: [ PUT ]
#  defaults: { auth: true }

search_post_comments:
  path: /post/{id}/comments
  controller: App\Apps\Web\Post\SearchPostComments\SearchPostCommentsController
  methods: [ GET ]
  defaults: { auth: true }

add_post_temporary_resource:
  path: /post/{id}/temporary-resource
  controller: App\Apps\Web\Post\AddPostTempResource\AddPostTemporaryResourceController
  methods: [ POST ]
  defaults: { auth: true }