create_post:
  path: /post
  controller: App\Apps\Web\Post\Create\CreatePostController
  methods: [ POST ]
  defaults: { auth: true }

find_post:
  path: /post/{id}
  controller: App\Apps\Web\Post\Find\FindPostController
  methods: [ GET ]
  defaults: { auth: true }

search_posts:
  path: /posts
  controller: App\Apps\Web\Post\Search\SearchPostsController
  methods: [ GET ]
  defaults: { auth: true }

add_post_comment:
  path: /post/{id}/comment
  controller: App\Apps\Web\Post\AddPostComment\AddPostCommentController
  methods: [ PUT ]
  defaults: { auth: true }

search_post_comments:
  path: /post/{id}/comments
  controller: App\Apps\Web\Post\SearchPostComments\SearchPostCommentsController
  methods: [ GET ]
  defaults: { auth: true }
