create_user:
  path: /user
  controller: App\Apps\Web\User\Create\CreateUserController
  methods: [ POST ]

find_user:
  path: /user/{id}
  controller: App\Apps\Web\User\Find\FindUserController
  methods: [ GET ]
  defaults: { auth: true }

find_user_by_username:
  path: /user/by-username/{username}
  controller: App\Apps\Web\User\FindByUsername\FindUserByUsernameController
  methods: [ GET ]
  defaults: { auth: true }

search_users:
  path: /users
  controller: App\Apps\Web\User\Search\SearchUsersController
  methods: [ GET ]
  defaults: { auth: true }

update_user:
  path: /user
  controller: App\Apps\Web\User\Update\UpdateUserController
  methods: [ PUT ]
  defaults: { auth: true }

update_user_password:
  path: /user/password/{id}
  controller: App\Apps\Web\User\UpdatePassword\UpdateUserPasswordController
  methods: [ PUT ]
  defaults: { auth: true }

user_restore:
  path: /user/{id}/restore
  controller: App\Apps\Web\User\RestorePassword\RestoreUserPasswordController
  methods: [ PUT ]

update_profile_image:
  path: /user-profile-image
  controller: App\Apps\Web\User\UpdateProfilePhoto\UpdateUserProfilePhotoController
  methods: [ POST ]
  defaults: { auth: true }

follow:
  path: /user/{id}/follow
  controller: App\Apps\Web\User\Follow\FollowUserController
  methods: [ PUT ]
  defaults: { auth: true }

unfollow:
  path: /user/{id}/unfollow
  controller: App\Apps\Web\User\Unfollow\UnfollowUserController
  methods: [ PUT ]
  defaults: { auth: true }

followings:
  path: /user/{id}/followings
  controller: App\Apps\Web\User\Followings\UserFollowingsController
  methods: [ GET ]
  defaults: { auth: true }

followers:
  path: /user/{id}/followers
  controller: App\Apps\Web\User\Followers\UserFollowersController
  methods: [ GET ]
  defaults: { auth: true }