search_social_networks:
    path: /user/social-network/search
    controller: App\Apps\Web\User\SocialNetwork\SearchSocialNetworksController
    methods: [GET]
    defaults: { auth: true }

add_user_social_network:
    path: /user/social-network/{socialNetworkId}/username/{username}
    controller: App\Apps\Web\User\SocialNetwork\AddUserSocialNetworkController
    methods: [PUT]
    defaults: { auth: true }

remove_user_social_network:
    path: /user/social-network/{socialNetworkId}
    controller: App\Apps\Web\User\SocialNetwork\RemoveUserSocialNetworkController
    methods: [DELETE]
    defaults: { auth: true }
