backoffice_search_users:
    path: /users
    controller: App\Apps\Backoffice\User\Search\SearchUsersController
    methods: [GET]
    defaults: { auth_admin: true }

backoffice_disable_user:
    path: /user/{id}/disable
    controller: App\Apps\Backoffice\User\Disable\DisableUserController
    methods: [POST]
    defaults: { auth_admin: true }

backoffice_enable_user:
    path: /user/{id}/enable
    controller: App\Apps\Backoffice\User\Enable\EnableUserController
    methods: [POST]
    defaults: { auth_admin: true }
